---
version: 2
project_name: xiond

env:
  - CGO_ENABLED=1
  - GO111MODULE=on

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

git:
  # sort tags in same commit
  # Source: https://goreleaser.com/customization/git/
  tag_sort: -version:creatordate

builds:
  - id: xiond
    main: ./cmd/xiond
    binary: xiond
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
    hooks:
      pre:
        - >-
          {{- if eq .Os "darwin" }}
            wget -q https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
          {{- else if eq .Os "linux" }}
            {{- if eq .Arch "amd64"}}
              wget -q https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.x86_64.a
            {{- else if eq .Arch "arm64"}}
              wget -q https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /lib/libwasmvm_muslc.aarch64.a
            {{- end }}
          {{- end }}
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++;
        flags:
          - -mod=readonly
          - -trimpath
        ldflags:
          - -X github.com/cosmos/cosmos-sdk/version.Name={{ .ProjectName }}
          - -X github.com/cosmos/cosmos-sdk/version.AppName={{ .ProjectName }}
          - -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }}
          - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
          - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
          - -w -s
          - -linkmode=external
          - -extldflags '-Wl,-z,muldefs -static -lm'
        tags:
          - netgo
          - ledger
          - muslc
          - osusergo
      - goos: linux
        goarch: amd64
        flags:
          - -mod=readonly
          - -trimpath
        ldflags:
          - -X github.com/cosmos/cosmos-sdk/version.Name={{ .ProjectName }}
          - -X github.com/cosmos/cosmos-sdk/version.AppName={{ .ProjectName }}
          - -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }}
          - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
          - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc
          - -w -s
          - -linkmode=external
          - -extldflags '-Wl,-z,muldefs -static -lm'
        tags:
          - netgo
          - ledger
          - muslc
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CGO_LDFLAGS=-L/lib
        flags:
          - -mod=readonly
          - -trimpath
        ldflags:
          - -X github.com/cosmos/cosmos-sdk/version.Name={{ .ProjectName }}
          - -X github.com/cosmos/cosmos-sdk/version.AppName={{ .ProjectName }}
          - -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }}
          - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
          - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
          - -w -s
          - -linkmode=external
        tags:
          - netgo
          - ledger
          - static_wasm
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
          - CGO_LDFLAGS=-L/lib
        flags:
          - -mod=readonly
          - -trimpath
        ldflags:
          - -X github.com/cosmos/cosmos-sdk/version.Name={{ .ProjectName }}
          - -X github.com/cosmos/cosmos-sdk/version.AppName={{ .ProjectName }}
          - -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }}
          - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
          - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
          - -w -s
          - -linkmode=external
        tags:
          - netgo
          - ledger
          - static_wasm
universal_binaries:
  - id: xiond
    replace: false
