// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xion/dkim/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca4ef5b8cd44607, []int{0}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgAddDkimPubKey is the Msg/AddDkimPubKey request type.
type MsgAddDkimPubKeys struct {
	// authority is the address of the governance account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// dkim_pubkeys defines the DKIM public keys to add.
	DkimPubkeys []DkimPubKey `protobuf:"bytes,2,rep,name=dkim_pubkeys,json=dkimPubkeys,proto3" json:"dkim_pubkeys"`
}

func (m *MsgAddDkimPubKeys) Reset()         { *m = MsgAddDkimPubKeys{} }
func (m *MsgAddDkimPubKeys) String() string { return proto.CompactTextString(m) }
func (*MsgAddDkimPubKeys) ProtoMessage()    {}
func (*MsgAddDkimPubKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca4ef5b8cd44607, []int{1}
}
func (m *MsgAddDkimPubKeys) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddDkimPubKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddDkimPubKeys.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddDkimPubKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddDkimPubKeys.Merge(m, src)
}
func (m *MsgAddDkimPubKeys) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddDkimPubKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddDkimPubKeys.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddDkimPubKeys proto.InternalMessageInfo

func (m *MsgAddDkimPubKeys) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgAddDkimPubKeys) GetDkimPubkeys() []DkimPubKey {
	if m != nil {
		return m.DkimPubkeys
	}
	return nil
}

// MsgAddDkimPubKeyResponse defines the response structure for executing a
// MsgAddDkimPubKey message.
type MsgAddDkimPubKeysResponse struct {
}

func (m *MsgAddDkimPubKeysResponse) Reset()         { *m = MsgAddDkimPubKeysResponse{} }
func (m *MsgAddDkimPubKeysResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddDkimPubKeysResponse) ProtoMessage()    {}
func (*MsgAddDkimPubKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca4ef5b8cd44607, []int{2}
}
func (m *MsgAddDkimPubKeysResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddDkimPubKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddDkimPubKeysResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddDkimPubKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddDkimPubKeysResponse.Merge(m, src)
}
func (m *MsgAddDkimPubKeysResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddDkimPubKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddDkimPubKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddDkimPubKeysResponse proto.InternalMessageInfo

// MsgRemoveDkimPubKey is the Msg/RemoveDkimPubKey request type.
type MsgRemoveDkimPubKey struct {
	// authority is the address of the governance account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// selector defines the DKIM selector to remove.
	Selector string `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	// domain defines the domain for the DKIM key to remove.
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (m *MsgRemoveDkimPubKey) Reset()         { *m = MsgRemoveDkimPubKey{} }
func (m *MsgRemoveDkimPubKey) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveDkimPubKey) ProtoMessage()    {}
func (*MsgRemoveDkimPubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca4ef5b8cd44607, []int{3}
}
func (m *MsgRemoveDkimPubKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveDkimPubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveDkimPubKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveDkimPubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveDkimPubKey.Merge(m, src)
}
func (m *MsgRemoveDkimPubKey) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveDkimPubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveDkimPubKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveDkimPubKey proto.InternalMessageInfo

func (m *MsgRemoveDkimPubKey) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRemoveDkimPubKey) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

func (m *MsgRemoveDkimPubKey) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

// MsgRemoveDkimPubKeyResponse defines the response structure for executing a
// MsgRemoveDkimPubKey message.
type MsgRemoveDkimPubKeyResponse struct {
}

func (m *MsgRemoveDkimPubKeyResponse) Reset()         { *m = MsgRemoveDkimPubKeyResponse{} }
func (m *MsgRemoveDkimPubKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveDkimPubKeyResponse) ProtoMessage()    {}
func (*MsgRemoveDkimPubKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca4ef5b8cd44607, []int{4}
}
func (m *MsgRemoveDkimPubKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveDkimPubKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveDkimPubKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveDkimPubKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveDkimPubKeyResponse.Merge(m, src)
}
func (m *MsgRemoveDkimPubKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveDkimPubKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveDkimPubKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveDkimPubKeyResponse proto.InternalMessageInfo

// MsgRevokeDkimPubKey is the Msg/RevokeDkimPubKey request type.
type MsgRevokeDkimPubKey struct {
	// signer defines the address of the signer revoking the key.
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// domain defines the domain for the DKIM key to revoke.
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// priv_key defines the private key used to prove ownership for revocation.
	PrivKey []byte `protobuf:"bytes,3,opt,name=priv_key,json=privKey,proto3" json:"priv_key,omitempty"`
}

func (m *MsgRevokeDkimPubKey) Reset()         { *m = MsgRevokeDkimPubKey{} }
func (m *MsgRevokeDkimPubKey) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeDkimPubKey) ProtoMessage()    {}
func (*MsgRevokeDkimPubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca4ef5b8cd44607, []int{5}
}
func (m *MsgRevokeDkimPubKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeDkimPubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeDkimPubKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeDkimPubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeDkimPubKey.Merge(m, src)
}
func (m *MsgRevokeDkimPubKey) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeDkimPubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeDkimPubKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeDkimPubKey proto.InternalMessageInfo

func (m *MsgRevokeDkimPubKey) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgRevokeDkimPubKey) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *MsgRevokeDkimPubKey) GetPrivKey() []byte {
	if m != nil {
		return m.PrivKey
	}
	return nil
}

// MsgRevokeDkimPubKeyResponse defines the response structure for executing a
// MsgRevokeDkimPubKey message.
type MsgRevokeDkimPubKeyResponse struct {
}

func (m *MsgRevokeDkimPubKeyResponse) Reset()         { *m = MsgRevokeDkimPubKeyResponse{} }
func (m *MsgRevokeDkimPubKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeDkimPubKeyResponse) ProtoMessage()    {}
func (*MsgRevokeDkimPubKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca4ef5b8cd44607, []int{6}
}
func (m *MsgRevokeDkimPubKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeDkimPubKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeDkimPubKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeDkimPubKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeDkimPubKeyResponse.Merge(m, src)
}
func (m *MsgRevokeDkimPubKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeDkimPubKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeDkimPubKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeDkimPubKeyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "xion.dkim.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgAddDkimPubKeys)(nil), "xion.dkim.v1.MsgAddDkimPubKeys")
	proto.RegisterType((*MsgAddDkimPubKeysResponse)(nil), "xion.dkim.v1.MsgAddDkimPubKeysResponse")
	proto.RegisterType((*MsgRemoveDkimPubKey)(nil), "xion.dkim.v1.MsgRemoveDkimPubKey")
	proto.RegisterType((*MsgRemoveDkimPubKeyResponse)(nil), "xion.dkim.v1.MsgRemoveDkimPubKeyResponse")
	proto.RegisterType((*MsgRevokeDkimPubKey)(nil), "xion.dkim.v1.MsgRevokeDkimPubKey")
	proto.RegisterType((*MsgRevokeDkimPubKeyResponse)(nil), "xion.dkim.v1.MsgRevokeDkimPubKeyResponse")
}

func init() { proto.RegisterFile("xion/dkim/v1/tx.proto", fileDescriptor_cca4ef5b8cd44607) }

var fileDescriptor_cca4ef5b8cd44607 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x3f, 0x6f, 0xd3, 0x40,
	0x18, 0xc6, 0xe3, 0x04, 0x42, 0x7b, 0x89, 0x2a, 0x30, 0x85, 0x3a, 0xae, 0x70, 0x4b, 0x96, 0x96,
	0x4a, 0xb5, 0x69, 0x91, 0x18, 0xba, 0x25, 0x62, 0xab, 0x22, 0x55, 0x46, 0x2c, 0x5d, 0x82, 0x1d,
	0x9f, 0xae, 0xa7, 0xd4, 0x3e, 0xeb, 0xde, 0xb3, 0x15, 0x6f, 0x88, 0x85, 0x15, 0xbe, 0x00, 0x9f,
	0x80, 0xa1, 0x03, 0x1f, 0xa2, 0x63, 0xc5, 0xc4, 0x84, 0x50, 0x32, 0xf4, 0x6b, 0xa0, 0xb3, 0x9d,
	0x3f, 0x8e, 0x23, 0x45, 0x62, 0xf3, 0xfb, 0x3e, 0xcf, 0x7b, 0xcf, 0x4f, 0x77, 0x7e, 0xd1, 0xb3,
	0x11, 0x65, 0x81, 0xe5, 0x0d, 0xa9, 0x6f, 0xc5, 0x27, 0x96, 0x18, 0x99, 0x21, 0x67, 0x82, 0xa9,
	0x4d, 0xd9, 0x36, 0x65, 0xdb, 0x8c, 0x4f, 0xf4, 0x9d, 0x01, 0x03, 0x9f, 0x81, 0xe5, 0x03, 0x91,
	0x2e, 0x1f, 0x48, 0x66, 0xd3, 0xf5, 0xc2, 0x34, 0xc1, 0x01, 0x06, 0x0a, 0xb9, 0xa6, 0x15, 0x34,
	0x10, 0x8e, 0xc0, 0xb9, 0xb2, 0x4d, 0x18, 0x61, 0xe9, 0xa7, 0x25, 0xbf, 0xf2, 0x6e, 0x2b, 0x0b,
	0xe9, 0x67, 0x42, 0x56, 0x64, 0x52, 0xbb, 0x85, 0x76, 0x7a, 0x40, 0x3e, 0x84, 0x9e, 0x23, 0xf0,
	0x85, 0xc3, 0x1d, 0x1f, 0x6c, 0x0c, 0x21, 0x0b, 0x00, 0xb7, 0xbf, 0x2b, 0xe8, 0x49, 0x0f, 0x48,
	0xc7, 0xf3, 0xde, 0x0d, 0xa9, 0x7f, 0x11, 0xb9, 0xe7, 0x38, 0x01, 0xf5, 0x2d, 0xda, 0x74, 0x22,
	0x71, 0xc5, 0x38, 0x15, 0x89, 0xa6, 0xec, 0x2b, 0x87, 0x9b, 0x5d, 0xed, 0xd7, 0xcf, 0xe3, 0xed,
	0xfc, 0xd4, 0x8e, 0xe7, 0x71, 0x0c, 0xf0, 0x5e, 0x70, 0x1a, 0x10, 0x7b, 0x6e, 0x55, 0x3b, 0xa8,
	0x29, 0x81, 0xfb, 0x61, 0xe4, 0x0e, 0x71, 0x02, 0x5a, 0x75, 0xbf, 0x76, 0xd8, 0x38, 0xd5, 0xcc,
	0xc5, 0xdb, 0x30, 0xe7, 0x41, 0xdd, 0x07, 0xb7, 0x7f, 0xf6, 0x2a, 0x76, 0xc3, 0xcb, 0x3a, 0x72,
	0xe4, 0x6c, 0xeb, 0xf3, 0xfd, 0xcd, 0xd1, 0xfc, 0xc8, 0xf6, 0x2e, 0x6a, 0x95, 0xf8, 0x66, 0xf4,
	0xdf, 0x14, 0xf4, 0xb4, 0x07, 0xc4, 0xc6, 0x3e, 0x8b, 0xf1, 0xdc, 0xf0, 0xdf, 0xfc, 0x3a, 0xda,
	0x00, 0x7c, 0x8d, 0x07, 0x82, 0x71, 0xad, 0x2a, 0xc7, 0xec, 0x59, 0xad, 0x3e, 0x47, 0x75, 0x8f,
	0xf9, 0x0e, 0x0d, 0xb4, 0x5a, 0xaa, 0xe4, 0x55, 0x09, 0xf8, 0x05, 0xda, 0x5d, 0x81, 0x34, 0x43,
	0xfe, 0x32, 0x45, 0x8e, 0xd9, 0x70, 0x11, 0xf9, 0x35, 0xaa, 0x03, 0x25, 0x01, 0xe6, 0x6b, 0x79,
	0x73, 0xdf, 0x02, 0x50, 0x75, 0x11, 0x48, 0x6d, 0xa1, 0x8d, 0x90, 0xd3, 0xb8, 0x3f, 0xc4, 0x49,
	0x8a, 0xda, 0xb4, 0x1f, 0xc9, 0xfa, 0x1c, 0x27, 0x67, 0x0d, 0xc9, 0x9a, 0xcf, 0xcf, 0x40, 0x8b,
	0x20, 0x53, 0xd0, 0xd3, 0x1f, 0x55, 0x54, 0xeb, 0x01, 0x51, 0x2f, 0xd1, 0xd6, 0xd2, 0xdf, 0xb1,
	0x57, 0x7c, 0xcf, 0xd2, 0xf3, 0xe8, 0x07, 0x6b, 0x0c, 0xd3, 0x0c, 0xf5, 0x23, 0x7a, 0x5c, 0x7a,
	0xbb, 0x97, 0xa5, 0xe1, 0x65, 0x8b, 0xfe, 0x6a, 0xad, 0xa5, 0x98, 0xb0, 0x74, 0xd5, 0xab, 0x12,
	0x8a, 0x96, 0x95, 0x09, 0xab, 0xef, 0x49, 0x7f, 0xf8, 0xe9, 0xfe, 0xe6, 0x48, 0xe9, 0x76, 0x6e,
	0xc7, 0x86, 0x72, 0x37, 0x36, 0x94, 0xbf, 0x63, 0x43, 0xf9, 0x3a, 0x31, 0x2a, 0x77, 0x13, 0xa3,
	0xf2, 0x7b, 0x62, 0x54, 0x2e, 0x0f, 0x08, 0x15, 0x57, 0x91, 0x6b, 0x0e, 0x98, 0x6f, 0xb9, 0x11,
	0x0f, 0xc4, 0xf1, 0xb5, 0xe3, 0x82, 0x95, 0xae, 0xf7, 0x28, 0x5b, 0x70, 0x91, 0x84, 0x18, 0xdc,
	0x7a, 0xba, 0xad, 0x6f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x55, 0x04, 0xfc, 0x54, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// AddDkimPubKey defines a message to add DKIM public keys.
	AddDkimPubKeys(ctx context.Context, in *MsgAddDkimPubKeys, opts ...grpc.CallOption) (*MsgAddDkimPubKeysResponse, error)
	// RemoveDkimPubKey defines a message to remove a DKIM public key via
	// governance
	RemoveDkimPubKey(ctx context.Context, in *MsgRemoveDkimPubKey, opts ...grpc.CallOption) (*MsgRemoveDkimPubKeyResponse, error)
	// RevokeDkimPubKey defines a message to remove a DKIM public key without
	// governance, by submitting the compromised privkey
	RevokeDkimPubKey(ctx context.Context, in *MsgRevokeDkimPubKey, opts ...grpc.CallOption) (*MsgRevokeDkimPubKeyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddDkimPubKeys(ctx context.Context, in *MsgAddDkimPubKeys, opts ...grpc.CallOption) (*MsgAddDkimPubKeysResponse, error) {
	out := new(MsgAddDkimPubKeysResponse)
	err := c.cc.Invoke(ctx, "/xion.dkim.v1.Msg/AddDkimPubKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveDkimPubKey(ctx context.Context, in *MsgRemoveDkimPubKey, opts ...grpc.CallOption) (*MsgRemoveDkimPubKeyResponse, error) {
	out := new(MsgRemoveDkimPubKeyResponse)
	err := c.cc.Invoke(ctx, "/xion.dkim.v1.Msg/RemoveDkimPubKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeDkimPubKey(ctx context.Context, in *MsgRevokeDkimPubKey, opts ...grpc.CallOption) (*MsgRevokeDkimPubKeyResponse, error) {
	out := new(MsgRevokeDkimPubKeyResponse)
	err := c.cc.Invoke(ctx, "/xion.dkim.v1.Msg/RevokeDkimPubKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// AddDkimPubKey defines a message to add DKIM public keys.
	AddDkimPubKeys(context.Context, *MsgAddDkimPubKeys) (*MsgAddDkimPubKeysResponse, error)
	// RemoveDkimPubKey defines a message to remove a DKIM public key via
	// governance
	RemoveDkimPubKey(context.Context, *MsgRemoveDkimPubKey) (*MsgRemoveDkimPubKeyResponse, error)
	// RevokeDkimPubKey defines a message to remove a DKIM public key without
	// governance, by submitting the compromised privkey
	RevokeDkimPubKey(context.Context, *MsgRevokeDkimPubKey) (*MsgRevokeDkimPubKeyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AddDkimPubKeys(ctx context.Context, req *MsgAddDkimPubKeys) (*MsgAddDkimPubKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDkimPubKeys not implemented")
}
func (*UnimplementedMsgServer) RemoveDkimPubKey(ctx context.Context, req *MsgRemoveDkimPubKey) (*MsgRemoveDkimPubKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDkimPubKey not implemented")
}
func (*UnimplementedMsgServer) RevokeDkimPubKey(ctx context.Context, req *MsgRevokeDkimPubKey) (*MsgRevokeDkimPubKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDkimPubKey not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AddDkimPubKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddDkimPubKeys)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddDkimPubKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xion.dkim.v1.Msg/AddDkimPubKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddDkimPubKeys(ctx, req.(*MsgAddDkimPubKeys))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveDkimPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveDkimPubKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveDkimPubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xion.dkim.v1.Msg/RemoveDkimPubKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveDkimPubKey(ctx, req.(*MsgRemoveDkimPubKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeDkimPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeDkimPubKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeDkimPubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xion.dkim.v1.Msg/RevokeDkimPubKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeDkimPubKey(ctx, req.(*MsgRevokeDkimPubKey))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xion.dkim.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDkimPubKeys",
			Handler:    _Msg_AddDkimPubKeys_Handler,
		},
		{
			MethodName: "RemoveDkimPubKey",
			Handler:    _Msg_RemoveDkimPubKey_Handler,
		},
		{
			MethodName: "RevokeDkimPubKey",
			Handler:    _Msg_RevokeDkimPubKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xion/dkim/v1/tx.proto",
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddDkimPubKeys) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddDkimPubKeys) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddDkimPubKeys) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DkimPubkeys) > 0 {
		for iNdEx := len(m.DkimPubkeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DkimPubkeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddDkimPubKeysResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddDkimPubKeysResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddDkimPubKeysResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRemoveDkimPubKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveDkimPubKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveDkimPubKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Selector) > 0 {
		i -= len(m.Selector)
		copy(dAtA[i:], m.Selector)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Selector)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveDkimPubKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveDkimPubKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveDkimPubKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRevokeDkimPubKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeDkimPubKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeDkimPubKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PrivKey) > 0 {
		i -= len(m.PrivKey)
		copy(dAtA[i:], m.PrivKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PrivKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevokeDkimPubKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeDkimPubKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeDkimPubKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddDkimPubKeys) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.DkimPubkeys) > 0 {
		for _, e := range m.DkimPubkeys {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgAddDkimPubKeysResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRemoveDkimPubKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Selector)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveDkimPubKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRevokeDkimPubKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PrivKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRevokeDkimPubKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddDkimPubKeys) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddDkimPubKeys: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddDkimPubKeys: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DkimPubkeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DkimPubkeys = append(m.DkimPubkeys, DkimPubKey{})
			if err := m.DkimPubkeys[len(m.DkimPubkeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddDkimPubKeysResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddDkimPubKeysResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddDkimPubKeysResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveDkimPubKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveDkimPubKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveDkimPubKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Selector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Selector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveDkimPubKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveDkimPubKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveDkimPubKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeDkimPubKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeDkimPubKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeDkimPubKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrivKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrivKey = append(m.PrivKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PrivKey == nil {
				m.PrivKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeDkimPubKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeDkimPubKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeDkimPubKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
