// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package xionv1

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_QueryWebAuthNVerifyRegisterRequest           protoreflect.MessageDescriptor
	fd_QueryWebAuthNVerifyRegisterRequest_addr      protoreflect.FieldDescriptor
	fd_QueryWebAuthNVerifyRegisterRequest_challenge protoreflect.FieldDescriptor
	fd_QueryWebAuthNVerifyRegisterRequest_rp        protoreflect.FieldDescriptor
	fd_QueryWebAuthNVerifyRegisterRequest_data      protoreflect.FieldDescriptor
)

func init() {
	file_xion_v1_query_proto_init()
	md_QueryWebAuthNVerifyRegisterRequest = File_xion_v1_query_proto.Messages().ByName("QueryWebAuthNVerifyRegisterRequest")
	fd_QueryWebAuthNVerifyRegisterRequest_addr = md_QueryWebAuthNVerifyRegisterRequest.Fields().ByName("addr")
	fd_QueryWebAuthNVerifyRegisterRequest_challenge = md_QueryWebAuthNVerifyRegisterRequest.Fields().ByName("challenge")
	fd_QueryWebAuthNVerifyRegisterRequest_rp = md_QueryWebAuthNVerifyRegisterRequest.Fields().ByName("rp")
	fd_QueryWebAuthNVerifyRegisterRequest_data = md_QueryWebAuthNVerifyRegisterRequest.Fields().ByName("data")
}

var _ protoreflect.Message = (*fastReflection_QueryWebAuthNVerifyRegisterRequest)(nil)

type fastReflection_QueryWebAuthNVerifyRegisterRequest QueryWebAuthNVerifyRegisterRequest

func (x *QueryWebAuthNVerifyRegisterRequest) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryWebAuthNVerifyRegisterRequest)(x)
}

func (x *QueryWebAuthNVerifyRegisterRequest) slowProtoReflect() protoreflect.Message {
	mi := &file_xion_v1_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryWebAuthNVerifyRegisterRequest_messageType fastReflection_QueryWebAuthNVerifyRegisterRequest_messageType
var _ protoreflect.MessageType = fastReflection_QueryWebAuthNVerifyRegisterRequest_messageType{}

type fastReflection_QueryWebAuthNVerifyRegisterRequest_messageType struct{}

func (x fastReflection_QueryWebAuthNVerifyRegisterRequest_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryWebAuthNVerifyRegisterRequest)(nil)
}
func (x fastReflection_QueryWebAuthNVerifyRegisterRequest_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryWebAuthNVerifyRegisterRequest)
}
func (x fastReflection_QueryWebAuthNVerifyRegisterRequest_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryWebAuthNVerifyRegisterRequest
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryWebAuthNVerifyRegisterRequest
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) Type() protoreflect.MessageType {
	return _fastReflection_QueryWebAuthNVerifyRegisterRequest_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) New() protoreflect.Message {
	return new(fastReflection_QueryWebAuthNVerifyRegisterRequest)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) Interface() protoreflect.ProtoMessage {
	return (*QueryWebAuthNVerifyRegisterRequest)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Addr != "" {
		value := protoreflect.ValueOfString(x.Addr)
		if !f(fd_QueryWebAuthNVerifyRegisterRequest_addr, value) {
			return
		}
	}
	if x.Challenge != "" {
		value := protoreflect.ValueOfString(x.Challenge)
		if !f(fd_QueryWebAuthNVerifyRegisterRequest_challenge, value) {
			return
		}
	}
	if x.Rp != "" {
		value := protoreflect.ValueOfString(x.Rp)
		if !f(fd_QueryWebAuthNVerifyRegisterRequest_rp, value) {
			return
		}
	}
	if len(x.Data) != 0 {
		value := protoreflect.ValueOfBytes(x.Data)
		if !f(fd_QueryWebAuthNVerifyRegisterRequest_data, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.addr":
		return x.Addr != ""
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.challenge":
		return x.Challenge != ""
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.rp":
		return x.Rp != ""
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.data":
		return len(x.Data) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterRequest does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.addr":
		x.Addr = ""
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.challenge":
		x.Challenge = ""
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.rp":
		x.Rp = ""
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.data":
		x.Data = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterRequest does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.addr":
		value := x.Addr
		return protoreflect.ValueOfString(value)
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.challenge":
		value := x.Challenge
		return protoreflect.ValueOfString(value)
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.rp":
		value := x.Rp
		return protoreflect.ValueOfString(value)
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.data":
		value := x.Data
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterRequest does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.addr":
		x.Addr = value.Interface().(string)
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.challenge":
		x.Challenge = value.Interface().(string)
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.rp":
		x.Rp = value.Interface().(string)
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.data":
		x.Data = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterRequest does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.addr":
		panic(fmt.Errorf("field addr of message xion.v1.QueryWebAuthNVerifyRegisterRequest is not mutable"))
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.challenge":
		panic(fmt.Errorf("field challenge of message xion.v1.QueryWebAuthNVerifyRegisterRequest is not mutable"))
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.rp":
		panic(fmt.Errorf("field rp of message xion.v1.QueryWebAuthNVerifyRegisterRequest is not mutable"))
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.data":
		panic(fmt.Errorf("field data of message xion.v1.QueryWebAuthNVerifyRegisterRequest is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterRequest does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.addr":
		return protoreflect.ValueOfString("")
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.challenge":
		return protoreflect.ValueOfString("")
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.rp":
		return protoreflect.ValueOfString("")
	case "xion.v1.QueryWebAuthNVerifyRegisterRequest.data":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterRequest does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in xion.v1.QueryWebAuthNVerifyRegisterRequest", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryWebAuthNVerifyRegisterRequest) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryWebAuthNVerifyRegisterRequest)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Addr)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Challenge)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Rp)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Data)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryWebAuthNVerifyRegisterRequest)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Data) > 0 {
			i -= len(x.Data)
			copy(dAtA[i:], x.Data)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Data)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Rp) > 0 {
			i -= len(x.Rp)
			copy(dAtA[i:], x.Rp)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Rp)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Challenge) > 0 {
			i -= len(x.Challenge)
			copy(dAtA[i:], x.Challenge)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Challenge)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Addr) > 0 {
			i -= len(x.Addr)
			copy(dAtA[i:], x.Addr)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Addr)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryWebAuthNVerifyRegisterRequest)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryWebAuthNVerifyRegisterRequest: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryWebAuthNVerifyRegisterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Addr = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Challenge", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Challenge = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Rp", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Rp = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Data = append(x.Data[:0], dAtA[iNdEx:postIndex]...)
				if x.Data == nil {
					x.Data = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_QueryWebAuthNVerifyRegisterResponse            protoreflect.MessageDescriptor
	fd_QueryWebAuthNVerifyRegisterResponse_credential protoreflect.FieldDescriptor
)

func init() {
	file_xion_v1_query_proto_init()
	md_QueryWebAuthNVerifyRegisterResponse = File_xion_v1_query_proto.Messages().ByName("QueryWebAuthNVerifyRegisterResponse")
	fd_QueryWebAuthNVerifyRegisterResponse_credential = md_QueryWebAuthNVerifyRegisterResponse.Fields().ByName("credential")
}

var _ protoreflect.Message = (*fastReflection_QueryWebAuthNVerifyRegisterResponse)(nil)

type fastReflection_QueryWebAuthNVerifyRegisterResponse QueryWebAuthNVerifyRegisterResponse

func (x *QueryWebAuthNVerifyRegisterResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryWebAuthNVerifyRegisterResponse)(x)
}

func (x *QueryWebAuthNVerifyRegisterResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_xion_v1_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryWebAuthNVerifyRegisterResponse_messageType fastReflection_QueryWebAuthNVerifyRegisterResponse_messageType
var _ protoreflect.MessageType = fastReflection_QueryWebAuthNVerifyRegisterResponse_messageType{}

type fastReflection_QueryWebAuthNVerifyRegisterResponse_messageType struct{}

func (x fastReflection_QueryWebAuthNVerifyRegisterResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryWebAuthNVerifyRegisterResponse)(nil)
}
func (x fastReflection_QueryWebAuthNVerifyRegisterResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryWebAuthNVerifyRegisterResponse)
}
func (x fastReflection_QueryWebAuthNVerifyRegisterResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryWebAuthNVerifyRegisterResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryWebAuthNVerifyRegisterResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) Type() protoreflect.MessageType {
	return _fastReflection_QueryWebAuthNVerifyRegisterResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) New() protoreflect.Message {
	return new(fastReflection_QueryWebAuthNVerifyRegisterResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) Interface() protoreflect.ProtoMessage {
	return (*QueryWebAuthNVerifyRegisterResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.Credential) != 0 {
		value := protoreflect.ValueOfBytes(x.Credential)
		if !f(fd_QueryWebAuthNVerifyRegisterResponse_credential, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterResponse.credential":
		return len(x.Credential) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterResponse.credential":
		x.Credential = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterResponse.credential":
		value := x.Credential
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterResponse.credential":
		x.Credential = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterResponse.credential":
		panic(fmt.Errorf("field credential of message xion.v1.QueryWebAuthNVerifyRegisterResponse is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyRegisterResponse.credential":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyRegisterResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyRegisterResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in xion.v1.QueryWebAuthNVerifyRegisterResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryWebAuthNVerifyRegisterResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryWebAuthNVerifyRegisterResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Credential)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryWebAuthNVerifyRegisterResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Credential) > 0 {
			i -= len(x.Credential)
			copy(dAtA[i:], x.Credential)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Credential)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryWebAuthNVerifyRegisterResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryWebAuthNVerifyRegisterResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryWebAuthNVerifyRegisterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Credential", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Credential = append(x.Credential[:0], dAtA[iNdEx:postIndex]...)
				if x.Credential == nil {
					x.Credential = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_QueryWebAuthNVerifyAuthenticateRequest            protoreflect.MessageDescriptor
	fd_QueryWebAuthNVerifyAuthenticateRequest_addr       protoreflect.FieldDescriptor
	fd_QueryWebAuthNVerifyAuthenticateRequest_challenge  protoreflect.FieldDescriptor
	fd_QueryWebAuthNVerifyAuthenticateRequest_rp         protoreflect.FieldDescriptor
	fd_QueryWebAuthNVerifyAuthenticateRequest_credential protoreflect.FieldDescriptor
	fd_QueryWebAuthNVerifyAuthenticateRequest_data       protoreflect.FieldDescriptor
)

func init() {
	file_xion_v1_query_proto_init()
	md_QueryWebAuthNVerifyAuthenticateRequest = File_xion_v1_query_proto.Messages().ByName("QueryWebAuthNVerifyAuthenticateRequest")
	fd_QueryWebAuthNVerifyAuthenticateRequest_addr = md_QueryWebAuthNVerifyAuthenticateRequest.Fields().ByName("addr")
	fd_QueryWebAuthNVerifyAuthenticateRequest_challenge = md_QueryWebAuthNVerifyAuthenticateRequest.Fields().ByName("challenge")
	fd_QueryWebAuthNVerifyAuthenticateRequest_rp = md_QueryWebAuthNVerifyAuthenticateRequest.Fields().ByName("rp")
	fd_QueryWebAuthNVerifyAuthenticateRequest_credential = md_QueryWebAuthNVerifyAuthenticateRequest.Fields().ByName("credential")
	fd_QueryWebAuthNVerifyAuthenticateRequest_data = md_QueryWebAuthNVerifyAuthenticateRequest.Fields().ByName("data")
}

var _ protoreflect.Message = (*fastReflection_QueryWebAuthNVerifyAuthenticateRequest)(nil)

type fastReflection_QueryWebAuthNVerifyAuthenticateRequest QueryWebAuthNVerifyAuthenticateRequest

func (x *QueryWebAuthNVerifyAuthenticateRequest) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryWebAuthNVerifyAuthenticateRequest)(x)
}

func (x *QueryWebAuthNVerifyAuthenticateRequest) slowProtoReflect() protoreflect.Message {
	mi := &file_xion_v1_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryWebAuthNVerifyAuthenticateRequest_messageType fastReflection_QueryWebAuthNVerifyAuthenticateRequest_messageType
var _ protoreflect.MessageType = fastReflection_QueryWebAuthNVerifyAuthenticateRequest_messageType{}

type fastReflection_QueryWebAuthNVerifyAuthenticateRequest_messageType struct{}

func (x fastReflection_QueryWebAuthNVerifyAuthenticateRequest_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryWebAuthNVerifyAuthenticateRequest)(nil)
}
func (x fastReflection_QueryWebAuthNVerifyAuthenticateRequest_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryWebAuthNVerifyAuthenticateRequest)
}
func (x fastReflection_QueryWebAuthNVerifyAuthenticateRequest_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryWebAuthNVerifyAuthenticateRequest
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryWebAuthNVerifyAuthenticateRequest
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) Type() protoreflect.MessageType {
	return _fastReflection_QueryWebAuthNVerifyAuthenticateRequest_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) New() protoreflect.Message {
	return new(fastReflection_QueryWebAuthNVerifyAuthenticateRequest)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) Interface() protoreflect.ProtoMessage {
	return (*QueryWebAuthNVerifyAuthenticateRequest)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Addr != "" {
		value := protoreflect.ValueOfString(x.Addr)
		if !f(fd_QueryWebAuthNVerifyAuthenticateRequest_addr, value) {
			return
		}
	}
	if x.Challenge != "" {
		value := protoreflect.ValueOfString(x.Challenge)
		if !f(fd_QueryWebAuthNVerifyAuthenticateRequest_challenge, value) {
			return
		}
	}
	if x.Rp != "" {
		value := protoreflect.ValueOfString(x.Rp)
		if !f(fd_QueryWebAuthNVerifyAuthenticateRequest_rp, value) {
			return
		}
	}
	if len(x.Credential) != 0 {
		value := protoreflect.ValueOfBytes(x.Credential)
		if !f(fd_QueryWebAuthNVerifyAuthenticateRequest_credential, value) {
			return
		}
	}
	if len(x.Data) != 0 {
		value := protoreflect.ValueOfBytes(x.Data)
		if !f(fd_QueryWebAuthNVerifyAuthenticateRequest_data, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.addr":
		return x.Addr != ""
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.challenge":
		return x.Challenge != ""
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.rp":
		return x.Rp != ""
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.credential":
		return len(x.Credential) != 0
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.data":
		return len(x.Data) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateRequest does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.addr":
		x.Addr = ""
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.challenge":
		x.Challenge = ""
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.rp":
		x.Rp = ""
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.credential":
		x.Credential = nil
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.data":
		x.Data = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateRequest does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.addr":
		value := x.Addr
		return protoreflect.ValueOfString(value)
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.challenge":
		value := x.Challenge
		return protoreflect.ValueOfString(value)
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.rp":
		value := x.Rp
		return protoreflect.ValueOfString(value)
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.credential":
		value := x.Credential
		return protoreflect.ValueOfBytes(value)
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.data":
		value := x.Data
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateRequest does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.addr":
		x.Addr = value.Interface().(string)
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.challenge":
		x.Challenge = value.Interface().(string)
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.rp":
		x.Rp = value.Interface().(string)
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.credential":
		x.Credential = value.Bytes()
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.data":
		x.Data = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateRequest does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.addr":
		panic(fmt.Errorf("field addr of message xion.v1.QueryWebAuthNVerifyAuthenticateRequest is not mutable"))
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.challenge":
		panic(fmt.Errorf("field challenge of message xion.v1.QueryWebAuthNVerifyAuthenticateRequest is not mutable"))
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.rp":
		panic(fmt.Errorf("field rp of message xion.v1.QueryWebAuthNVerifyAuthenticateRequest is not mutable"))
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.credential":
		panic(fmt.Errorf("field credential of message xion.v1.QueryWebAuthNVerifyAuthenticateRequest is not mutable"))
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.data":
		panic(fmt.Errorf("field data of message xion.v1.QueryWebAuthNVerifyAuthenticateRequest is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateRequest does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.addr":
		return protoreflect.ValueOfString("")
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.challenge":
		return protoreflect.ValueOfString("")
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.rp":
		return protoreflect.ValueOfString("")
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.credential":
		return protoreflect.ValueOfBytes(nil)
	case "xion.v1.QueryWebAuthNVerifyAuthenticateRequest.data":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateRequest"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateRequest does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in xion.v1.QueryWebAuthNVerifyAuthenticateRequest", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateRequest) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryWebAuthNVerifyAuthenticateRequest)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Addr)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Challenge)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Rp)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Credential)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Data)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryWebAuthNVerifyAuthenticateRequest)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Data) > 0 {
			i -= len(x.Data)
			copy(dAtA[i:], x.Data)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Data)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Credential) > 0 {
			i -= len(x.Credential)
			copy(dAtA[i:], x.Credential)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Credential)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Rp) > 0 {
			i -= len(x.Rp)
			copy(dAtA[i:], x.Rp)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Rp)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Challenge) > 0 {
			i -= len(x.Challenge)
			copy(dAtA[i:], x.Challenge)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Challenge)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Addr) > 0 {
			i -= len(x.Addr)
			copy(dAtA[i:], x.Addr)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Addr)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryWebAuthNVerifyAuthenticateRequest)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryWebAuthNVerifyAuthenticateRequest: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryWebAuthNVerifyAuthenticateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Addr = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Challenge", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Challenge = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Rp", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Rp = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Credential", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Credential = append(x.Credential[:0], dAtA[iNdEx:postIndex]...)
				if x.Credential == nil {
					x.Credential = []byte{}
				}
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Data = append(x.Data[:0], dAtA[iNdEx:postIndex]...)
				if x.Data == nil {
					x.Data = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_QueryWebAuthNVerifyAuthenticateResponse protoreflect.MessageDescriptor
)

func init() {
	file_xion_v1_query_proto_init()
	md_QueryWebAuthNVerifyAuthenticateResponse = File_xion_v1_query_proto.Messages().ByName("QueryWebAuthNVerifyAuthenticateResponse")
}

var _ protoreflect.Message = (*fastReflection_QueryWebAuthNVerifyAuthenticateResponse)(nil)

type fastReflection_QueryWebAuthNVerifyAuthenticateResponse QueryWebAuthNVerifyAuthenticateResponse

func (x *QueryWebAuthNVerifyAuthenticateResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryWebAuthNVerifyAuthenticateResponse)(x)
}

func (x *QueryWebAuthNVerifyAuthenticateResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_xion_v1_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryWebAuthNVerifyAuthenticateResponse_messageType fastReflection_QueryWebAuthNVerifyAuthenticateResponse_messageType
var _ protoreflect.MessageType = fastReflection_QueryWebAuthNVerifyAuthenticateResponse_messageType{}

type fastReflection_QueryWebAuthNVerifyAuthenticateResponse_messageType struct{}

func (x fastReflection_QueryWebAuthNVerifyAuthenticateResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryWebAuthNVerifyAuthenticateResponse)(nil)
}
func (x fastReflection_QueryWebAuthNVerifyAuthenticateResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryWebAuthNVerifyAuthenticateResponse)
}
func (x fastReflection_QueryWebAuthNVerifyAuthenticateResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryWebAuthNVerifyAuthenticateResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryWebAuthNVerifyAuthenticateResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) Type() protoreflect.MessageType {
	return _fastReflection_QueryWebAuthNVerifyAuthenticateResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) New() protoreflect.Message {
	return new(fastReflection_QueryWebAuthNVerifyAuthenticateResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) Interface() protoreflect.ProtoMessage {
	return (*QueryWebAuthNVerifyAuthenticateResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: xion.v1.QueryWebAuthNVerifyAuthenticateResponse"))
		}
		panic(fmt.Errorf("message xion.v1.QueryWebAuthNVerifyAuthenticateResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in xion.v1.QueryWebAuthNVerifyAuthenticateResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryWebAuthNVerifyAuthenticateResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryWebAuthNVerifyAuthenticateResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryWebAuthNVerifyAuthenticateResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryWebAuthNVerifyAuthenticateResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryWebAuthNVerifyAuthenticateResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryWebAuthNVerifyAuthenticateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: xion/v1/query.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryWebAuthNVerifyRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr      string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Challenge string `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Rp        string `protobuf:"bytes,3,opt,name=rp,proto3" json:"rp,omitempty"`
	Data      []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *QueryWebAuthNVerifyRegisterRequest) Reset() {
	*x = QueryWebAuthNVerifyRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xion_v1_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryWebAuthNVerifyRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWebAuthNVerifyRegisterRequest) ProtoMessage() {}

// Deprecated: Use QueryWebAuthNVerifyRegisterRequest.ProtoReflect.Descriptor instead.
func (*QueryWebAuthNVerifyRegisterRequest) Descriptor() ([]byte, []int) {
	return file_xion_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryWebAuthNVerifyRegisterRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *QueryWebAuthNVerifyRegisterRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *QueryWebAuthNVerifyRegisterRequest) GetRp() string {
	if x != nil {
		return x.Rp
	}
	return ""
}

func (x *QueryWebAuthNVerifyRegisterRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryWebAuthNVerifyRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credential []byte `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *QueryWebAuthNVerifyRegisterResponse) Reset() {
	*x = QueryWebAuthNVerifyRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xion_v1_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryWebAuthNVerifyRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWebAuthNVerifyRegisterResponse) ProtoMessage() {}

// Deprecated: Use QueryWebAuthNVerifyRegisterResponse.ProtoReflect.Descriptor instead.
func (*QueryWebAuthNVerifyRegisterResponse) Descriptor() ([]byte, []int) {
	return file_xion_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryWebAuthNVerifyRegisterResponse) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

type QueryWebAuthNVerifyAuthenticateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr       string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Challenge  string `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Rp         string `protobuf:"bytes,3,opt,name=rp,proto3" json:"rp,omitempty"`
	Credential []byte `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	Data       []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *QueryWebAuthNVerifyAuthenticateRequest) Reset() {
	*x = QueryWebAuthNVerifyAuthenticateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xion_v1_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryWebAuthNVerifyAuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWebAuthNVerifyAuthenticateRequest) ProtoMessage() {}

// Deprecated: Use QueryWebAuthNVerifyAuthenticateRequest.ProtoReflect.Descriptor instead.
func (*QueryWebAuthNVerifyAuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_xion_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryWebAuthNVerifyAuthenticateRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *QueryWebAuthNVerifyAuthenticateRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *QueryWebAuthNVerifyAuthenticateRequest) GetRp() string {
	if x != nil {
		return x.Rp
	}
	return ""
}

func (x *QueryWebAuthNVerifyAuthenticateRequest) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *QueryWebAuthNVerifyAuthenticateRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryWebAuthNVerifyAuthenticateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryWebAuthNVerifyAuthenticateResponse) Reset() {
	*x = QueryWebAuthNVerifyAuthenticateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xion_v1_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryWebAuthNVerifyAuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWebAuthNVerifyAuthenticateResponse) ProtoMessage() {}

// Deprecated: Use QueryWebAuthNVerifyAuthenticateResponse.ProtoReflect.Descriptor instead.
func (*QueryWebAuthNVerifyAuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_xion_v1_query_proto_rawDescGZIP(), []int{3}
}

var File_xion_v1_query_proto protoreflect.FileDescriptor

var file_xion_v1_query_proto_rawDesc = []byte{
	0x0a, 0x13, 0x78, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x78, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x7a,
	0x0a, 0x22, 0x51, 0x75, 0x65, 0x72, 0x79, 0x57, 0x65, 0x62, 0x41, 0x75, 0x74, 0x68, 0x4e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x72, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x23, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x57, 0x65, 0x62, 0x41, 0x75, 0x74, 0x68, 0x4e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x22, 0x9e, 0x01, 0x0a, 0x26, 0x51, 0x75, 0x65, 0x72, 0x79, 0x57, 0x65, 0x62, 0x41, 0x75,
	0x74, 0x68, 0x4e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x72, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x72, 0x70, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x29, 0x0a, 0x27, 0x51, 0x75, 0x65, 0x72, 0x79, 0x57, 0x65, 0x62, 0x41, 0x75,
	0x74, 0x68, 0x4e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x82, 0x02,
	0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x75, 0x0a, 0x16, 0x57, 0x65, 0x62, 0x41, 0x75,
	0x74, 0x68, 0x4e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x2b, 0x2e, 0x78, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x57, 0x65, 0x62, 0x41, 0x75, 0x74, 0x68, 0x4e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c,
	0x2e, 0x78, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x57, 0x65,
	0x62, 0x41, 0x75, 0x74, 0x68, 0x4e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x81,
	0x01, 0x0a, 0x1a, 0x57, 0x65, 0x62, 0x41, 0x75, 0x74, 0x68, 0x4e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x2f, 0x2e,
	0x78, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x57, 0x65, 0x62,
	0x41, 0x75, 0x74, 0x68, 0x4e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30,
	0x2e, 0x78, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x57, 0x65,
	0x62, 0x41, 0x75, 0x74, 0x68, 0x4e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x85, 0x01, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x42, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x72,
	0x6e, 0x74, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x78, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x78, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x78, 0x69, 0x6f, 0x6e, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x58, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x58, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x07, 0x58, 0x69, 0x6f, 0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x13, 0x58, 0x69, 0x6f, 0x6e,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x08, 0x58, 0x69, 0x6f, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_xion_v1_query_proto_rawDescOnce sync.Once
	file_xion_v1_query_proto_rawDescData = file_xion_v1_query_proto_rawDesc
)

func file_xion_v1_query_proto_rawDescGZIP() []byte {
	file_xion_v1_query_proto_rawDescOnce.Do(func() {
		file_xion_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_xion_v1_query_proto_rawDescData)
	})
	return file_xion_v1_query_proto_rawDescData
}

var file_xion_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xion_v1_query_proto_goTypes = []interface{}{
	(*QueryWebAuthNVerifyRegisterRequest)(nil),      // 0: xion.v1.QueryWebAuthNVerifyRegisterRequest
	(*QueryWebAuthNVerifyRegisterResponse)(nil),     // 1: xion.v1.QueryWebAuthNVerifyRegisterResponse
	(*QueryWebAuthNVerifyAuthenticateRequest)(nil),  // 2: xion.v1.QueryWebAuthNVerifyAuthenticateRequest
	(*QueryWebAuthNVerifyAuthenticateResponse)(nil), // 3: xion.v1.QueryWebAuthNVerifyAuthenticateResponse
}
var file_xion_v1_query_proto_depIdxs = []int32{
	0, // 0: xion.v1.Query.WebAuthNVerifyRegister:input_type -> xion.v1.QueryWebAuthNVerifyRegisterRequest
	2, // 1: xion.v1.Query.WebAuthNVerifyAuthenticate:input_type -> xion.v1.QueryWebAuthNVerifyAuthenticateRequest
	1, // 2: xion.v1.Query.WebAuthNVerifyRegister:output_type -> xion.v1.QueryWebAuthNVerifyRegisterResponse
	3, // 3: xion.v1.Query.WebAuthNVerifyAuthenticate:output_type -> xion.v1.QueryWebAuthNVerifyAuthenticateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xion_v1_query_proto_init() }
func file_xion_v1_query_proto_init() {
	if File_xion_v1_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xion_v1_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryWebAuthNVerifyRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xion_v1_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryWebAuthNVerifyRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xion_v1_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryWebAuthNVerifyAuthenticateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xion_v1_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryWebAuthNVerifyAuthenticateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xion_v1_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xion_v1_query_proto_goTypes,
		DependencyIndexes: file_xion_v1_query_proto_depIdxs,
		MessageInfos:      file_xion_v1_query_proto_msgTypes,
	}.Build()
	File_xion_v1_query_proto = out.File
	file_xion_v1_query_proto_rawDesc = nil
	file_xion_v1_query_proto_goTypes = nil
	file_xion_v1_query_proto_depIdxs = nil
}
