// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: xion/zk/v1/tx.proto

package zkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_AddVKey_FullMethodName    = "/xion.zk.v1.Msg/AddVKey"
	Msg_UpdateVKey_FullMethodName = "/xion.zk.v1.Msg/UpdateVKey"
	Msg_RemoveVKey_FullMethodName = "/xion.zk.v1.Msg/RemoveVKey"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the Msg service.
type MsgClient interface {
	// AddVKey adds a new verification key
	AddVKey(ctx context.Context, in *MsgAddVKey, opts ...grpc.CallOption) (*MsgAddVKeyResponse, error)
	// UpdateVKey updates an existing verification key
	UpdateVKey(ctx context.Context, in *MsgUpdateVKey, opts ...grpc.CallOption) (*MsgUpdateVKeyResponse, error)
	// RemoveVKey removes a verification key
	RemoveVKey(ctx context.Context, in *MsgRemoveVKey, opts ...grpc.CallOption) (*MsgRemoveVKeyResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddVKey(ctx context.Context, in *MsgAddVKey, opts ...grpc.CallOption) (*MsgAddVKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgAddVKeyResponse)
	err := c.cc.Invoke(ctx, Msg_AddVKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateVKey(ctx context.Context, in *MsgUpdateVKey, opts ...grpc.CallOption) (*MsgUpdateVKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateVKeyResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateVKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveVKey(ctx context.Context, in *MsgRemoveVKey, opts ...grpc.CallOption) (*MsgRemoveVKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRemoveVKeyResponse)
	err := c.cc.Invoke(ctx, Msg_RemoveVKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the Msg service.
type MsgServer interface {
	// AddVKey adds a new verification key
	AddVKey(context.Context, *MsgAddVKey) (*MsgAddVKeyResponse, error)
	// UpdateVKey updates an existing verification key
	UpdateVKey(context.Context, *MsgUpdateVKey) (*MsgUpdateVKeyResponse, error)
	// RemoveVKey removes a verification key
	RemoveVKey(context.Context, *MsgRemoveVKey) (*MsgRemoveVKeyResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) AddVKey(context.Context, *MsgAddVKey) (*MsgAddVKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVKey not implemented")
}
func (UnimplementedMsgServer) UpdateVKey(context.Context, *MsgUpdateVKey) (*MsgUpdateVKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVKey not implemented")
}
func (UnimplementedMsgServer) RemoveVKey(context.Context, *MsgRemoveVKey) (*MsgRemoveVKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveVKey not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_AddVKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddVKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddVKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddVKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddVKey(ctx, req.(*MsgAddVKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateVKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateVKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateVKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateVKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateVKey(ctx, req.(*MsgUpdateVKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveVKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveVKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveVKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RemoveVKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveVKey(ctx, req.(*MsgRemoveVKey))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xion.zk.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddVKey",
			Handler:    _Msg_AddVKey_Handler,
		},
		{
			MethodName: "UpdateVKey",
			Handler:    _Msg_UpdateVKey_Handler,
		},
		{
			MethodName: "RemoveVKey",
			Handler:    _Msg_RemoveVKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xion/zk/v1/tx.proto",
}
