## NOTICE: This file gets embedded into interchaintest binary.
## Set the environment variable: IBCTEST_CONFIGURED_CHAINS to a path
## to use custom versions of this file

osmosis:
  name: osmosis
  type: cosmos
  bin: osmosisd
  bech32-prefix: osmo
  denom: uosmo
  gas-prices: 0.0025uosmo
  gas-adjustment: 1.3
  trusting-period: 336h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/osmosis
      version: v28.0.0
      uid-gid: 1025:1025
  no-host-mount: false

xion:
  name: xion
  type: cosmos
  bin: xiond
  bech32-prefix: xion
  denom: uxion
  gas-prices: 0.0uxion
  gas-adjustment: 1.3
  trusting-period: 336h
  images:
    - repository: ghcr.io/burnt-labs/xion/heighliner
      version: v20.0.0
      uid-gid: 1025:1025
  no-host-mount: false
