name: Build Linux Binaries

# reusable workflow, do not add triggers
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-binaries:
    name: Build xiond-${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'arm64' && format('github-{0}', matrix.arch) || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
        arch:
          - amd64
          - arm64
    
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Go Version
        run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build Linux Binary
        env: 
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
        run: |
          make build-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: xiond-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/**/xiond-${{ matrix.os }}-${{ matrix.arch }}
          retention-days: 3
          if-no-files-found: error
