name: Docker Scout

# reusable workflow, do not add triggers
on:
  workflow_call:

jobs:
  docker-scout:
    name: Docker Scout
    runs-on: ubuntu-latest
    environment: CI
    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Get Docker Image
        id: meta-scout
        uses: docker/metadata-action@v5
        with:
          images: |
            burntnetwork/xion
          tags: |
            type=sha
      - name: Run Docker Scout amd64
        uses: docker/scout-action@v1
        with:
          command: cves
          only-fixed: true
          platform: ${{ matrix.platform }}
          image: ${{ steps.meta-scout.outputs.tags }}
