---
name: Docker Scout

on:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    name: Docker Scout
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: burnt/xion
          tags: |
            type=raw,value=scout,priority=1000

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: xion-release

      - name: Run Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          only-fixed: true
          image: ${{ steps.meta.outputs.tags }}
