name: Heighliner Build, Push & Scout

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: Build Linux Binaries
    uses: ./.github/workflows/binaries-linux.yaml
    secrets: inherit

  build-heighliner:
    name: Build Heighliner ${{ matrix.os }}/${{ matrix.arch }}
    needs: build-linux
    runs-on: ${{ format('github-{0}', matrix.arch) }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
        arch:
          - amd64
          - arm64

    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx for push
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          platforms: ${{ matrix.os }}/${{ matrix.arch }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: xiond-${{ matrix.os }}-${{ matrix.arch }}
          merge-multiple: true

      - name: Prepare environment
        run: |
          echo "HEIGHLINER_FN=heighliner-${{ matrix.os }}-${{ matrix.arch }}.tar" | tee -a $GITHUB_ENV
          echo "PREBUILT_BINARY=$(find dist -name xiond-${{ matrix.os }}-${{ matrix.arch}})" | tee -a $GITHUB_ENV

      - name: Build Heighliner Image
        id: build-heighliner
        uses: docker/build-push-action@v5
        with:
          context: .
          target: heighliner
          push: false
          load: true
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          tags: heighliner:${{ matrix.os }}-${{ matrix.arch }}
          build-args: |
            COMMIT=${{ github.sha }}
            VERSION=${{ github.ref_name }}
            PREBUILT_BINARY=${{ env.PREBUILT_BINARY }}

      - name: Save Heighliner Image
        working-directory: ${{ runner.temp }}
        run: |
          docker save heighliner:${{ matrix.os }}-${{ matrix.arch }} > ${{ env.HEIGHLINER_FN }}

      - name: Upload Heighliner Image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.HEIGHLINER_FN }}
          path: ${{ runner.temp }}/${{ env.HEIGHLINER_FN }}
          if-no-files-found: error
          retention-days: 3

  push-heighliner:
    name: Push Heighliner Images
    needs: build-heighliner
    uses: ./.github/workflows/heighliner-push.yaml
    secrets: inherit

  docker-scout:
    name: Docker Scout
    needs: build-heighliner
    uses: ./.github/workflows/docker-scout.yaml
    secrets: inherit
