name: Heighliner Build

# reusable workflow, do not add triggers
on:
  workflow_dispatch:

env:
  GHCR: ghcr.io/${{ github.repository }}
  PLATFORMS: linux/amd64

jobs:
  build-heighliner:
    name: Heighliner Build
    runs-on: ubuntu-latest
    environment: CI
    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Metadata for heighliner
        id: meta-heighliner
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR }}/heighliner
          tags: |
            type=sha
            type=semver,pattern={{version}},enable=${{ github.event_name == 'push' }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build Heighliner image
        id: heighliner
        uses: burnt-labs/heighliner-action@v1.0.0-alpha10
        with:
          local: true
          tag: ${{ steps.meta-heighliner.outputs.tags }}
          chain: xion
          dockerfile: import
          platform: ${{ env.PLATFORMS }}
          binaries: '["/usr/bin/xiond"]'
          build-env: "[\"BUILD_TAGS=muslc\", \"BASE_IMAGE=${{ env.GHCR }}/xion\", \"VERSION=${{ fromJSON(steps.meta-heighliner.outputs.json).labels['org.opencontainers.image.version'] }}\"]"

      - name: Push Heighliner image
        run: |
          docker push ghcr.io/burnt-labs/xion/${{ steps.heighliner.outputs.tag }}
