name: Heighliner Build

on:
  workflow_dispatch:

env:
  GHCR: ghcr.io/${{ github.repository }}
  PLATFORMS: linux/amd64

jobs:
  build-docker:
    name: Build and Push Docker Images
    uses: burnt-labs/xion/.github/workflows/docker-build.yml@wf1
    secrets: inherit

  build-heighliner:
    needs: build-docker
    name: Heighliner Build
    uses: burnt-labs/xion/.github/workflows/heighliner.yml@wf1
    secrets: inherit