name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-docker:
    name: Build Docker Images
    uses: burnt-labs/xion/.github/workflows/docker-build.yml@wf1
    secrets: inherit

  docker-scout:
    needs: build-docker
    name: Docker Scout
    uses: burnt-labs/xion/.github/workflows/docker-scout.yml@wf1
    secrets: inherit

  build-heighliner:
    needs: build-docker
    name: Heighliner Build
    uses: burnt-labs/xion/.github/workflows/heighliner.yml@wf1
    secrets: inherit

  interchain-tests:
    needs: build-heighliner
    name: Interchain tests
    uses: burnt-labs/xion/.github/workflows/integration-tests.yml@wf1
    secrets: inherit