name: Unit Tests

# reusable workflow, do not add triggers
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-cover:
    name: Coverage
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'

      - name: Prepare Environment
        run: |
          sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod | tee -a "$GITHUB_ENV"

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Install clang and libc++
        if: steps.changes.outputs.go == 'true'
        run: |
          sudo rm -f /etc/apt/sources.list.d/google-chrome*.list
          sudo apt-get update && sudo apt-get install -y --no-install-recommends clang libc++-dev libc++abi-dev

      - name: Build Barretenberg wrapper
        if: steps.changes.outputs.go == 'true'
        run: make barretenberg-build-wrapper

      - name: Test with coverage
        if: steps.changes.outputs.go == 'true'
        run: make test-cover-ci

  test-race:
    name: Race detection
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'

      - name: Prepare Environment
        run: |
          sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod | tee -a "$GITHUB_ENV"

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Install clang and libc++
        if: steps.changes.outputs.go == 'true'
        run: |
          sudo rm -f /etc/apt/sources.list.d/google-chrome*.list
          sudo apt-get update && sudo apt-get install -y --no-install-recommends clang libc++-dev libc++abi-dev

      - name: Build Barretenberg wrapper
        if: steps.changes.outputs.go == 'true'
        run: make barretenberg-build-wrapper

      - name: Test with race detector
        if: steps.changes.outputs.go == 'true'
        run: go test ./... -race -timeout=30m -tags='ledger test_ledger_mock' -ldflags="-w"
