name: Trigger Types

on:
  workflow_call:
    inputs:
      release_tag:
        description: "Release tag (e.g. v28.0.0)"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag (e.g. v28.0.0)"
        required: true
        type: string

jobs:
  release-types:
    name: Release Types
    uses: burnt-labs/xion-types/.github/workflows/release.yaml@main
    with:
      release_tag: ${{ inputs.release_tag }}
    secrets: inherit
